[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
version = "0.10.3"

[profile.release]
opt-level = 2 # fast and small wasm

[profile.wasm-release]
inherits = "release"

opt-level = "z"
lto = "fat"
codegen-units = 1
