[workspace]
version = "0.9.0"
members = ["crates/*"]
resolver = "2"

[profile.release]
opt-level = 2 # fast and small wasm

[profile.wasm-release]
inherits = "release"

opt-level = "z"
lto = "fat"
codegen-units = 1
