[toolchain]
channel = "nightly"
components = [
    "rustc",
    "cargo",
    "clippy",
    "rust-analysis",
    "rust-src",
    "rustfmt",
    "llvm-tools-preview",
]
targets = [
    "x86_64-unknown-linux-gnu",
    "wasm32-unknown-unknown",
]
profile = "minimal"
