name: CD

on:
  push:
    branches:
      master

jobs:
  bump-version:
    name: bump version
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: configure git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com

      - name: Install nix
        uses: cachix/install-nix-action@v15
        with:
          extra_nix_config: |
            access-tokens = github=${{ secrets.GITHUB_TOKEN }}

      - name: Setup nix cache
        uses: cachix/cachix-action@v10
        with:
          name: justinrubek
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: bump version
        run: nix develop -c cog bump --auto

      - name: push updates
        run: |
          git push
          git push --tags
