name: CI

on: push

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install nix
        uses: cachix/install-nix-action@v15
        with:
          extra_nix_config: |
            access-tokens = github=${{ secrets.GITHUB_TOKEN }}

      - name: Setup nix cache
        uses: cachix/cachix-action@v10
        with:
          name: justinrubek
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: test
        run: nix develop -c cargo test
