name: Release
on:
  push:
    tags:
      - "*"

jobs:
  publish-release:
    name: publish release
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Install nix
        uses: cachix/install-nix-action@v15
        with:
          extra_nix_config: |
            access-tokens = github=${{ secrets.GITHUB_TOKEN }}

      - name: Setup nix cache
        uses: cachix/cachix-action@v10
        with:
          name: justinrubek
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: get version
        id: get-version
        run: |
          VERSION=`git describe --tags $(git rev-list --tags --max-count=1)`
          echo ::set-output name=version::"$VERSION"

      - name: generate changelog
        env:
          VERSION: ${{ steps.get-version.outputs.version }}
        run: |
          nix develop -c cog changelog --at $VERSION -t full_hash > GITHUB_CHANGELOG.md

      - name: generate release
        uses: softprops/action-gh-release@v1
        with:
          body_path: GITHUB_CHANGELOG.md
          tag_name: ${{ steps.get-version.outputs.version }}

  publish-wasm:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Install nix
        uses: cachix/install-nix-action@v15
        with:
          extra_nix_config: |
            access-tokens = github=${{ secrets.GITHUB_TOKEN }}

      - name: Setup nix cache
        uses: cachix/cachix-action@v10
        with:
          name: justinrubek
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Build package
        run:
          nix build .#client-wasm

      - name: copy files
        run: |
          cp ./result/wasm/client.js public
          cp ./result/wasm/client_bg.wasm public

      - name: deploy to pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
